appearance:
  theme: Default
  button_style: IconAndText
display:
  answer_bold: true
  answer_fontsize_pt: 14
  font: Hack
  fraction_bold: false
  fraction_fontsize_pt: 10
  fraction_small_fontsize_pt: 8
  max_denominator_digits: 12
  question_bold: false
  question_fontsize_pt: 10
  short_units: false
entry:
  bold: true
  font: Hack
  fontsize_pt: 12
  show_execution_errors: true
  view_line_highlighting: true
execution:
  precision: 30
  simplify_units: true
