name: Darkish
style:
  background: '#242424'
  background_alt: '#2c2c2c'
  error: "color: '#e03838'"
  literal: "color: '#f0f0f0'"
  variable: "color: '#4890ff'"
  constant: "color: '#a870e8'"
  structural: "color: '#c04090'"
  function: "color: '#e07830'"
  special: "color: '#00b8b8'"
  comment: "color: '#909090'"
