name: Default
style:
  background: '#ffffff'
  background_alt: '#f0f0f0'
  error: "color: '#c03030'"
  literal: "color: '#202020'"
  variable: "color: '#3030c0'"
  constant: "color: '#7020a8'"
  structural: "color: '#800000'"
  function: "color: '#a05010'"
  special: "color: '#007070'"
  comment: "color: '#808080'"
