name: Default
light:
  error: "color: '#bc0000'"
  default: "color: '#bc0000'"
  literal: "color: '#097e00'"
  unit: "color: '#805f00'"
  unitsystem: "color: '#805f00'"
  op: "color: '#0c0c0c'"
  terminator: "color: '#0c0c0c'"
  inner_expr_start: "color: '#0c0c0c'"
  inner_expr_end: "color: '#0c0c0c'"
  function_name: "color: '#00297f'"
  function_start: "color: '#0c0c0c'"
  function_param: "color: '#0c0c0c'"
  function_end: "color: '#0c0c0c'"
  ext_function_name: "color: '#00297f'"
  variable: "color: '#480081'"
  constant: "color: '#812500'"
  comment: "color: '#007d80'"
dark:
  error: "color: '#cd0d0d'"
  default: "color: '#cd2727'"
  literal: "color: '#3ae42d'"
  unit: "color: '#d7a40e'"
  unitsystem: "color: '#d7a40e'"
  op: "color: '#f2f2f2'"
  terminator: "color: '#f2f2f2'"
  inner_expr_start: "color: '#f2f2f2'"
  inner_expr_end: "color: '#f2f2f2'"
  function_name: "color: '#3577ff'"
  function_start: "color: '#f2f2f2'"
  function_param: "color: '#f2f2f2'"
  function_end: "color: '#f2f2f2'"
  ext_function_name: "color: '#3577ff'"
  variable: "color: '#a839ff'"
  constant: "color: '#ff6629'"
  comment: "color: '#2ee5e9'"
