name: Default
style:
  background: '#ffffff'
  background_alt: '#f0f0f0'
  error: "color: '#c03030'"
  default: "color: '#c03030'"
  literal: "color: '#202020'"
  unit: "color: '#007070'"
  unitsystem: "color: '#007070'"
  numericalrepresentation: "color: '#007070'"
  op: "color: '#800000'"
  terminator: "color: '#800000'"
  inner_expr_start: "color: '#800000'"
  inner_expr_end: "color: '#800000'"
  function_name: "color: '#a05010'"
  function_start: "color: '#800000'"
  function_param: "color: '#800000'"
  function_end: "color: '#800000'"
  array_start: "color: '#800000'"
  array_range: "color: '#800000'"
  array_step: "color: '#800000'"
  array_param: "color: '#800000'"
  array_end: "color: '#800000'"
  ext_function_name: "color: '#a05010'"
  variable: "color: '#3030c0'"
  constant: "color: '#7020a8'"
  comment: "color: '#808080'"
