name: Dracula
style:
  background: '#282A36'
  background_alt: '#30323E'
  error: "color: '#F83333'"
  literal: "color: '#F8F8F0'"
  variable: "color: '#6898ff'"
  constant: "color: '#BD93F9'"
  structural: "color: '#999a9e'"
  function: "color: '#FFB86C'"
  special: "color: '#6BE5FD'"
  comment: "color: '#6272A4'"
