name: Dracula
style:
  background: '#282A36'
  background_alt: '#30323E'
  error: "color: '#F83333'"
  default: "color: '#F83333'"
  literal: "color: '#F8F8F0'"
  unit: "color: '#6BE5FD'"
  unitsystem: "color: '#6BE5FD'"
  numericalrepresentation: "color: '#6BE5FD'"
  op: "color: '#999a9e'"
  terminator: "color: '#999a9e'"
  inner_expr_start: "color: '#999a9e'"
  inner_expr_end: "color: '#999a9e'"
  function_name: "color: '#FFB86C'"
  function_start: "color: '#999a9e'"
  function_param: "color: '#999a9e'"
  function_end: "color: '#999a9e'"
  array_start: "color: '#999a9e'"
  array_range: "color: '#999a9e'"
  array_step: "color: '#999a9e'"
  array_param: "color: '#999a9e'"
  array_end: "color: '#999a9e'"
  ext_function_name: "color: '#FFB86C'"
  variable: "color: '#6898ff'"
  constant: "color: '#BD93F9'"
  comment: "color: '#6272A4'"
