name: Github
style:
  background: '#FFFFFF'
  background_alt: '#ECECEC'
  error: "color: '#F93232'"
  literal: "color: '#333333'"
  variable: "color: '#183691'"
  constant: "color: '#795DA3'"
  structural: "color: '#A71D5D'"
  function: "color: '#DF5000'"
  special: "color: '#009926'"
  comment: "color: '#969896'"
