name: High Contrast White
style:
  background: '#ffffff'
  background_alt: '#e8e8e8'
  error: "color: '#b00000'"
  literal: "color: '#000000'"
  variable: "color: '#0000a0'"
  constant: "color: '#0000a0'"
  structural: "color: '#700070'"
  function: "color: '#0000a0'"
  special: "color: '#0000a0'"
  comment: "color: '#007070'"
