name: High Contrast White
style:
  background: '#ffffff'
  background_alt: '#e8e8e8'
  error: "color: '#b00000'"
  default: "color: '#b00000'"
  literal: "color: '#000000'"
  unit: "color: '#0000a0'"
  unitsystem: "color: '#0000a0'"
  op: "color: '#700070'"
  terminator: "color: '#000000'"
  inner_expr_start: "color: '#700070'"
  inner_expr_end: "color: '#700070'"
  function_name: "color: '#0000a0'"
  function_start: "color: '#700070'"
  function_param: "color: '#700070'"
  function_end: "color: '#700070'"
  array_start: "color: '#700070'"
  array_range: "color: '#700070'"
  array_step: "color: '#700070'"
  array_param: "color: '#700070'"
  array_end: "color: '#700070'"
  ext_function_name: "color: '#0000a0'"
  variable: "color: '#0000a0'"
  constant: "color: '#0000a0'"
  comment: "color: '#007070'"
