name: High Contrast Black
style:
  background: '#000000'
  background_alt: '#181818'
  error: "color: '#ff3838'"
  literal: "color: '#ffffff'"
  variable: "color: '#ffff00'"
  constant: "color: '#ffff00'"
  structural: "color: '#ff00ff'"
  function: "color: '#ffff00'"
  special: "color: '#ffff00'"
  comment: "color: '#00ffff'"
