name: Material Light
style:
  background: '#FFFFFF'
  background_alt: '#F0F0F0'
  error: "color: '#E53935'"
  literal: "color: '#607D8B'"
  variable: "color: '#6182B8'"
  constant: "color: '#7C4DFF'"
  structural: "color: '#009688'"
  function: "color: '#C17E70'"
  special: "color: '#91B859'"
  comment: "color: '#8796B0'"
