name: Material Dark
style:
  background: '#202226'
  background_alt: '#282a2e'
  error: "color: '#e03838'"
  literal: "color: '#DDDDDD'"
  variable: "color: '#4890ff'"
  constant: "color: '#C792EA'"
  structural: "color: '#FF5370'"
  function: "color: '#F78C6A'"
  special: "color: '#009688'"
  comment: "color: '#B2CCD6'"
