name: Material Dark
style:
  background: '#202226'
  background_alt: '#282a2e'
  error: "color: '#e03838'"
  default: "color: '#e03030'"
  literal: "color: '#DDDDDD'"
  unit: "color: '#009688'"
  unitsystem: "color: '#009688'"
  numericalrepresentation: "color: '#009688'"
  op: "color: '#FF5370'"
  terminator: "color: '#FF5370'"
  inner_expr_start: "color: '#FF5370'"
  inner_expr_end: "color: '#FF5370'"
  function_name: "color: '#F78C6A'"
  function_start: "color: '#FF5370'"
  function_param: "color: '#FF5370'"
  function_end: "color: '#FF5370'"
  array_start: "color: '#FF5370'"
  array_range: "color: '#FF5370'"
  array_step: "color: '#FF5370'"
  array_param: "color: '#FF5370'"
  array_end: "color: '#FF5370'"
  ext_function_name: "color: '#F78C6A'"
  variable: "color: '#4890ff'"
  constant: "color: '#C792EA'"
  comment: "color: '#B2CCD6'"
