name: Monochrome White
style:
  background: '#ffffff'
  background_alt: '#e8e8e8'
  error: "color: '#606060'"
  literal: "color: '#000000'"
  variable: "color: '#000000'"
  constant: "color: '#000000'"
  structural: "color: '#000000'"
  function: "color: '#000000'"
  special: "color: '#000000'"
  comment: "color: '#000000'"
