name: Monochrome Black
style:
  background: '#000000'
  background_alt: '#181818'
  error: "color: '#a0a0a0'"
  default: "color: '#a0a0a0'"
  literal: "color: '#ffffff'"
  unit: "color: '#ffffff'"
  unitsystem: "color: '#ffffff'"
  op: "color: '#ffffff'"
  terminator: "color: '#ffffff'"
  inner_expr_start: "color: '#ffffff'"
  inner_expr_end: "color: '#ffffff'"
  function_name: "color: '#ffffff'"
  function_start: "color: '#ffffff'"
  function_param: "color: '#ffffff'"
  function_end: "color: '#ffffff'"
  array_start: "color: '#ffffff'"
  array_range: "color: '#ffffff'"
  array_step: "color: '#ffffff'"
  array_param: "color: '#ffffff'"
  array_end: "color: '#ffffff'"
  ext_function_name: "color: '#ffffff'"
  variable: "color: '#ffffff'"
  constant: "color: '#ffffff'"
  comment: "color: '#ffffff'"
