name: Monochrome
light:
  error: "color: '#bc0000'"
  default: "color: '#000000'"
  literal: "color: '#000000'"
  unit: "color: '#000000'"
  unitsystem: "color: '#000000'"
  op: "color: '#000000'"
  terminator: "color: '#000000'"
  inner_expr_start: "color: '#000000'"
  inner_expr_end: "color: '#000000'"
  function_name: "color: '#000000'"
  function_start: "color: '#000000'"
  function_param: "color: '#000000'"
  function_end: "color: '#000000'"
  ext_function_name: "color: '#000000'"
  variable: "color: '#000000'"
  constant: "color: '#000000'"
  comment: "color: '#000000'"
dark:
  error: "color: '#cd0d0d'"
  default: "color: '#ffffff'"
  literal: "color: '#ffffff'"
  unit: "color: '#ffffff'"
  unitsystem: "color: '#ffffff'"
  op: "color: '#ffffff'"
  terminator: "color: '#ffffff'"
  inner_expr_start: "color: '#ffffff'"
  inner_expr_end: "color: '#ffffff'"
  function_name: "color: '#ffffff'"
  function_start: "color: '#ffffff'"
  function_param: "color: '#ffffff'"
  function_end: "color: '#ffffff'"
  ext_function_name: "color: '#ffffff'"
  variable: "color: '#ffffff'"
  constant: "color: '#ffffff'"
  comment: "color: '#ffffff'"
