name: Monochrome Black
style:
  background: '#000000'
  background_alt: '#181818'
  error: "color: '#a0a0a0'"
  literal: "color: '#ffffff'"
  variable: "color: '#ffffff'"
  constant: "color: '#ffffff'"
  structural: "color: '#ffffff'"
  function: "color: '#ffffff'"
  special: "color: '#ffffff'"
  comment: "color: '#ffffff'"
