name: Tango
style:
  background: '#000000'
  background_alt: '#101010'
  error: "color: '#ef2929'"
  literal: "color: '#eeeeec'"
  variable: "color: '#ad7fa8'"
  constant: "color: '#fce94f'"
  structural: "color: '#729fcf'"
  function: "color: '#729fcf'"
  special: "color: '#8ae234'"
  comment: "color: '#34e2e2'"
